title: vinit ravishankar
# baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/"
 - name: "resume"
   link: "resume.pdf"
